### ISSUE TITLE
Melhorar organização do requirements

### ISSUE THREAD

**Issue by exageraldo** [jerimumhs/transparencia-api#10]
Os projetos python geralmente usam um arquivo requirements para colocar todas as suas dependências. Quando possui alguma dependência de desenvolvimento ou ferramentas para depuração, cria-se outro arquivo chamado requirements-dev.txt. Não é necessário colocar o gunicorn como dependência, é opção de cada pessoa escolher em qual servidor rodar a aplicação.

**Comment by rodrigondec** [comment]
No caso então da configuração de desenvolvimento local é usado o `pip install -r requirements.txt`e `pip install -r requirements-dev.txt` logo em seguida?

**Comment by exageraldo** [comment]
No caso, é só instalar o `requirements-dev.txt` ele já instala o `requirements` tbm. 

[Veja aqui](https://github.com/jerimumhs/transparencia-api/blob/refactor/requirements/requirements-dev.txt#L1)

**Comment by rodrigondec** [comment]
Entendi. Fica melhor assim mesmo :top:
