### ISSUE TITLE
Modificar o Makefile para rodar localmente

### ISSUE THREAD

**Issue by exageraldo** [jerimumhs/transparencia-api#12]
Modificar o Makefile para rodar localmente (não dentro do docker). Deixar o docker para fazer o ambiente de desenvolvimento com maior compatibilidade com o ambiente de produção, ou para pessoas que não queiram configurar o ambiente para rodar o sistema.

É possivel rodar os comandos do Makefile dentro do container, já que o arquivo tambem se encontrará lá dentro. Dando liberdade para rodar os comandos onde quiser.

**Comment by rodrigondec** [comment]
Sem nenhum problema em manter esses comandos para controle local.
Porém gostaria de deixar os comandos relativos ao docker também. Podem ficar tipo `docker.up` ao invés de apenas `up` como estava antes.

O motivo disse é que controlaremos o docker de um bash normal, e não de um bash dentro do container. 

Então não tem ganho de praticidade (para utilização do docker) chamar o `make db.migrate` como está atualmente, pq eu teria que acessar o bash de algum container usando `docker-compose run api-server bash` e dpois sim chamar o `make db.migrate`.

Outra questão é o set-env. Acho melhor deixar separado. Preciso utilizar o comando de copiar o `.env.example` na configuração pra rodar o container, então não preciso rodar o `pip install` pq vou rodar o container. Isso vai impactar no CI que vai rodar nos containers, então ele vai dar erro se tentar rodar o `pip install`.
