### ISSUE TITLE
Desacoplar a configuração da aplicação do código

### ISSUE THREAD

**Issue by exageraldo** [jerimumhs/transparencia-api#14]
Desacoplar a responsabilidade das configurações do código de dentro do proprio código. Uma boa sugestão é o `dynaconf`. 

https://dynaconf.readthedocs.io/en/latest/

https://github.com/rochacbruno/dynaconf/blob/master/docs/guides/flask.md

**Comment by rodrigondec** [comment]
Achei interessante. Porém não estou gostando do seguindo fato:

Esse dynaconf não utiliza varíavel de ambiente para realizar a configuração, ele utiliza o arquivo de configuração apenas. 
Ou seja, se for mudar alguma configuração precisa alterar no arquivo. Logo se cada desenvolvedor  configurar de uma maneira o seu banco de dados cada um vai precisar do seu próprio arquivo de configuração. 

Talvez seja possível configurar um arquivo de configuração adicional que seja apenas local e que não vá para o repositório (pelo que li por cima da lib).

Mas vai continuar precisando criar esse arquivo local e alterando ele se for preciso. E no ambiente de produção no servidor? Qualquer PaaS ou IaaS fornece configuração de varíavel de ambiente e é mt mais simples de utilizar/configurar.

Utilizando o Dynaconf a gente vai continuar configurando o projeto pelo Python, ao invés de utilizar variáveis de ambiente.

Para demostrar o que estou querendo dizer estou mandando umas imagens aqui.

### Configuração do app flask e print de varíaveis de ambiente da execução
![image](https://user-images.githubusercontent.com/3301060/66156220-9de19400-e5f7-11e9-91dd-76dcc3622ebc.png)

### Saída do `flask run`
![image](https://user-images.githubusercontent.com/3301060/66156178-8e624b00-e5f7-11e9-8976-7857d97d2300.png)

###  Configuração das varíaveis de ambiente
![image](https://user-images.githubusercontent.com/3301060/66156285-c4073400-e5f7-11e9-934a-ad2d1490f91c.png)

### Arquivo de configuração utilizado no Dynaconf
![image](https://user-images.githubusercontent.com/3301060/66156297-c9fd1500-e5f7-11e9-8454-c571bcf01427.png)

**Comment by exageraldo** [comment]
O dynaconf lê sim os arquivos .env (https://dynaconf.readthedocs.io/en/latest/guides/usage.html#illustrative-example), mas como possui dados sensiveis, coloquei o `SQLALCHEMY_DATABASE_URI` em um arquivo chamado .secrets.toml . Não vejo necessidade de quebrar a URI em HOST, PORT, NAME, USER, PASSWORD nas variaveis, se vamos usar elas juntas. Se quiser configurar assim, dê uma olhada no `SQLALCHEMY_ENGINE_OPTIONS`

**Comment by exageraldo** [comment]
Mas teremos sim, dois arquivos que teremos que configurar que são `.env` e o `.secrets.toml`, mas tambem pode se configurar o arquivo `settings.toml`. Mas dessa forma, as configurações ficam na responsabilidade dos configs e não do python.

**Comment by rodrigondec** [comment]
Alterei as configurações no #18 para utilizar environment variables

Li as seguintes fontes antes de tomar essa decisão:
- https://simpleit.rocks/python/flask/avoid-using-flask-instance-folder-when-deploying-to-heroku/
- https://www.pythonanywhere.com/forums/topic/963/https://medium.com/@aswens0276/refactoring-python-flask-environment-variables-with-environs-module-d0e1850c89eb
- https://flask.palletsprojects.com/en/1.1.x/config/
