### ISSUE TITLE
Melhorar o docker-compose da aplicação

### ISSUE THREAD

**Issue by exageraldo** [jerimumhs/transparencia-api#8]
O docker-compose pode ser melhorado de algumas formas, a primeira delas é colocando a identação de 4 para 2 espaços (padrão indicado para arquivos .yml). 
Outra indicação é remover o pgadmin. As alterações devem ser feitas diretas pelo código, para poder ficar o registro no log.
Tambem remover o diretorio chamado `docker/` e incluir tudo no proprio compose. Centralizar as configurações.

**Comment by fguisso** [comment]
Não existe uma imagem do flask já pronta, para não ter q criar um dockerfile?
se tiver fica mais facil, o docker-compose já puxa direto.

Agora as variaveis de ambiente é crucial pra segurança, login e senha no .git não pode ter não.

O `pgadmin` é só para consultar o banco? se for isso tem q ser instalado na maquina de quem for acessar o banco, não é uma boa pratica deixar um client para o banco aberto ao publico. Podemos deixar um tutorial de como rodar o pgadmin localmente pra acessar o banco depois.

**Comment by exageraldo** [comment]
@fguisso Então, não tem nenhuma imagem oficial do Flask. Estava pensando em deixar o docker mais como opção alternativa, porque deixaremos sempre o compose compatível, que facilita para o ambiente de desenvolvimento e pessoas que queiram uma opção fácil de configurar. 

Eu vou configurar o dynaconf para não subir dados sensíveis para o repositório.

Exatamente, melhor retirar daqui e deixar escrito como conectar usando a ferramenta. Acho que fica melhor mesmo.

**Comment by rodrigondec** [comment]
Sim, o PGAdmin era apenas para facilitar no inicio. Inclusive ele nem rodaria onde nossa aplicação fosse servida.

**Comment by rodrigondec** [comment]
@exageraldo Concordo com as configurações sensíveis. Inclusive Está configurado como varíavel de env os dados de acesso ao banco para isso. E está apenas com um login e senha default, subindo a gente iria alterar isso.

Já sobre o docker, é necessário continuar tendo o dockerfile para ficar em cache as libs instaladas pelo pipy. Se não toda vez que iniciar o container ele vai ter que instalar todas as bibliotecas.

Vou voltar o Dockerfile e parametrizar a config de acesso do postgres
